name: Deploy
run-name: "Deploy: make new release for ${{ github.ref_name }}"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:    
  release:
    name: Deploy the new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Set up app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BOT_APPID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Make a new release
        id: release-drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          name: '${{ github.ref_name }}'
          tag: '${{ github.ref_name }}'
          publish: true
          disable-autolabeler: true

          
      # - name: Create a new release
      #   id: create-release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: v1.0.0
      #     release_name: Release v1.0.0
      #     body: |
      #       Changes in this release:
      #       - Feature 1
      #       - Feature 2
      #     draft: false
      #     prerelease: false
      #     token: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Upload artifacts
      #   id: upload-artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: release-artifacts