name: Deploy
run-name: "Deploy: Make new release for ${{ github.ref_name }}"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:    
  release:
    name: Deploy the new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Set up app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BOT_APPID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Make a new release
        id: release-drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          name: '${{ github.ref_name }}'
          tag: '${{ github.ref_name }}'
          publish: true
          disable-autolabeler: true
      
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          upload_url: ${{ steps.release-drafter.outputs.upload_url }}
          asset_path: ./version.txt
          asset_name: version.txt
          asset_content_type: plain/text