name: Prevent direct changes to changelog

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check for changelog changes
      run: |
        echo "This is just a behavior test."
        exit 1
