name: Merge release branch

on:
  workflow_run:
    workflows: ["Test on release branch"]
    types:
      - completed

jobs:
  check-previous-workflow:
    name: Check if the previous workflow succeeded
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' }}
    steps:
      - name: Check the result of the previous workflow
        id: check-prev-result
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "::error::The triggering workflow 'Test on release branch' did not pass."
            exit 1
          fi

  release-merge:
    name: Merge Release Branch to main and develop
    runs-on: ubuntu-latest
    if: ${{ ! failure() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get release branch name
        id: get-branch
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///')
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Extract version number from branch name
        id: get-version
        run: |
          VERSION=$(echo "${{ env.branch_name }}" | sed 's/release\/v//')
          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Update version.txt
        run: |
          echo "${{ env.version }}" > version.txt
          git add version.txt
          git commit -m "Update version to ${{ env.version }}"

      - name: Push changes to release branch
        run: |
          git push origin "${{ env.branch_name }}"

      - name: Merge release branch to main
        run: |
          git checkout main
          git merge --no-ff "${{ env.branch_name }}"
          git push origin main

      - name: Merge release branch to develop
        run: |
          git checkout develop
          git merge --no-ff "${{ env.branch_name }}"
          git push origin develop

      - name: Delete release branch
        run: |
          git push origin --delete "${{ env.branch_name }}"
