name: PR status check
run-name: "Check: Prevent version changes in PRs"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  prevent-version-change:
    name: No version modification
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      id: checkout-repo
      uses: actions/checkout@v4
    
    - name: Check for changelog changes
      id: check-version
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'version.txt'; then
          echo "Version changes are not allowed. Please revert them."
          exit 1
        fi
